Change the function validLib to improve the code efficiency.
lephare-photoz/lephare pull request #255
Opened 2024-12-10 14:47 UTC by olivierilbert

Change the function validLib in onesource.cpp. Rather than providing fullLib as an argument, I passed the redshift from the library. The price for manipulating the large vector of complex objects (fullLib) was slowing down the code. With this modification, we gain almost a factor 3 in speed when zfix=yes. Results are exactly the same. I think that such change could be done in few other functions.

2024-12-11 22:25 UTC, johannct approved these changes
LGTM but we can push a bit forward :
- you mention a few other places where this could be done. It is the right place to do it
- zfix arg in validLib is not really sound. In photoz_lib zfix should be tested and validLib called only when zfix==true. Note that a vector with the first N integers is obtained with std::iota : 
`#include <numeric> 
std::vector<int> vec(fullLib.size());
   // fills the vector from 1 to N
   std::iota(vec.begin(), vec.end(), 1);
`
- a unit test is easy to build and should be done
- should we take this opportunity to write a notebook that shows the usefulness of running with zfix==yes?

2024-12-12 15:37 UTC, johannct commented
As a matter of fact the management of zfix is problematic in other places as well. For instance onesource::interp is really tortuous

2024-12-12 15:40 UTC, johannct commented
the fact that the argument of validLib is incorrect and that the fix is not applied in the notebook blocks the approval.

2024-12-13 17:59 UTC, olivierilbert commented
I managed an extremely significant gain in speed (more than a factor 10) by changing the initialization of a vector. It should also help in case of ZFIX=NO, but it should be shown. 

The results are unchanged comparing the masses and SFR of 10000 sources between the vesrion currently on the main and this one.

I consider the problem of speed resolved in case of ZFIX=YES.

Next step before finalizing the merge (after the comments of Johann):
- Include one example of ZFIX=YES in the notebook, for physical parameters
- change the notebooks/Testing_fit_of_one_object_of_the_catalogue.ipynb to avoid craching the pre-commit
- Add a unit test

2024-12-16 08:46 UTC, olivierilbert commented
Invert interp and generatePDF because the function int_parab() needs the PDF.

2024-12-16 14:51 UTC, olivierilbert commented
All the changes in the way of initialize the vector (and remove some useless ones) have help a lot in making the code faster. But there is still a problem with the pre-commit, and _bindings.cc. Johann, any idea?

2024-12-18 07:34 UTC, johannct requested changes
in fitIR :
`      if (fulllibIR[i]->red == closest_red) {`

2024-12-18 08:04 UTC, johannct approved these changes
I propose that after the change request I just made this branch be merged, so that we can see if the coverage issue is a fluke. I checked a clean version of the branch out and ould not reproduce it....

2024-12-18 11:15 UTC, olivierilbert commented
I did all the requested change, and correct the bug#258. All the results look fine and no problem with the unit_test and pre-commit locally. I still have the same problem in the unit test with _bindinc.cc.

2024-12-18 11:28 UTC, johannct approved these changes
LGTM

2024-12-18 14:45 UTC, merged